//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserMS.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RadControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadControlResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserMS.Localization.RadControlResources", typeof(RadControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 世纪 的本地化字符串。
        /// </summary>
        public static string Century {
            get {
                return ResourceManager.GetString("Century", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DecadeEnding 的本地化字符串。
        /// </summary>
        public static string DecadeEnding {
            get {
                return ResourceManager.GetString("DecadeEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与 的本地化字符串。
        /// </summary>
        public static string FilterAnd {
            get {
                return ResourceManager.GetString("FilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含 的本地化字符串。
        /// </summary>
        public static string FilterContains {
            get {
                return ResourceManager.GetString("FilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包括 的本地化字符串。
        /// </summary>
        public static string FilterDoesNotContain {
            get {
                return ResourceManager.GetString("FilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结尾是 的本地化字符串。
        /// </summary>
        public static string FilterEndsWith {
            get {
                return ResourceManager.GetString("FilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含在 的本地化字符串。
        /// </summary>
        public static string FilterIsContainedIn {
            get {
                return ResourceManager.GetString("FilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是空 的本地化字符串。
        /// </summary>
        public static string FilterIsEmpty {
            get {
                return ResourceManager.GetString("FilterIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相等 的本地化字符串。
        /// </summary>
        public static string FilterIsEqualTo {
            get {
                return ResourceManager.GetString("FilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public static string FilterIsGreaterThan {
            get {
                return ResourceManager.GetString("FilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于等于 的本地化字符串。
        /// </summary>
        public static string FilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        public static string FilterIsLessThan {
            get {
                return ResourceManager.GetString("FilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于等于 的本地化字符串。
        /// </summary>
        public static string FilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含在 的本地化字符串。
        /// </summary>
        public static string FilterIsNotContainedIn {
            get {
                return ResourceManager.GetString("FilterIsNotContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不为空 的本地化字符串。
        /// </summary>
        public static string FilterIsNotEmpty {
            get {
                return ResourceManager.GetString("FilterIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        public static string FilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("FilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不为 Null 的本地化字符串。
        /// </summary>
        public static string FilterIsNotNull {
            get {
                return ResourceManager.GetString("FilterIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为 Null 的本地化字符串。
        /// </summary>
        public static string FilterIsNull {
            get {
                return ResourceManager.GetString("FilterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区分大小写 的本地化字符串。
        /// </summary>
        public static string FilterMatchCase {
            get {
                return ResourceManager.GetString("FilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或 的本地化字符串。
        /// </summary>
        public static string FilterOr {
            get {
                return ResourceManager.GetString("FilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头是 的本地化字符串。
        /// </summary>
        public static string FilterStartsWith {
            get {
                return ResourceManager.GetString("FilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击新增 的本地化字符串。
        /// </summary>
        public static string GridViewAlwaysVisibleNewRow {
            get {
                return ResourceManager.GetString("GridViewAlwaysVisibleNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空筛选 的本地化字符串。
        /// </summary>
        public static string GridViewClearFilter {
            get {
                return ResourceManager.GetString("GridViewClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        public static string GridViewFilter {
            get {
                return ResourceManager.GetString("GridViewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与 的本地化字符串。
        /// </summary>
        public static string GridViewFilterAnd {
            get {
                return ResourceManager.GetString("GridViewFilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含 的本地化字符串。
        /// </summary>
        public static string GridViewFilterContains {
            get {
                return ResourceManager.GetString("GridViewFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含 的本地化字符串。
        /// </summary>
        public static string GridViewFilterDoesNotContain {
            get {
                return ResourceManager.GetString("GridViewFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结尾是 的本地化字符串。
        /// </summary>
        public static string GridViewFilterEndsWith {
            get {
                return ResourceManager.GetString("GridViewFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含在 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是空 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsEmpty {
            get {
                return ResourceManager.GetString("GridViewFilterIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相等 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsGreaterThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于等于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsLessThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于等于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含在 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsNotContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不为空 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsNotEmpty {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不为空值 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsNotNull {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为空值 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsNull {
            get {
                return ResourceManager.GetString("GridViewFilterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区分大小写 的本地化字符串。
        /// </summary>
        public static string GridViewFilterMatchCase {
            get {
                return ResourceManager.GetString("GridViewFilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或 的本地化字符串。
        /// </summary>
        public static string GridViewFilterOr {
            get {
                return ResourceManager.GetString("GridViewFilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string GridViewFilterSelectAll {
            get {
                return ResourceManager.GetString("GridViewFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按以下条件筛选 的本地化字符串。
        /// </summary>
        public static string GridViewFilterShowRowsWithValueThat {
            get {
                return ResourceManager.GetString("GridViewFilterShowRowsWithValueThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头是 的本地化字符串。
        /// </summary>
        public static string GridViewFilterStartsWith {
            get {
                return ResourceManager.GetString("GridViewFilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头是 的本地化字符串。
        /// </summary>
        public static string GridViewFilterStartsWith1 {
            get {
                return ResourceManager.GetString("GridViewFilterStartsWith1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头是 的本地化字符串。
        /// </summary>
        public static string GridViewFilterStartsWith2 {
            get {
                return ResourceManager.GetString("GridViewFilterStartsWith2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖动标题到此处分组 的本地化字符串。
        /// </summary>
        public static string GridViewGroupPanelText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组 的本地化字符串。
        /// </summary>
        public static string GridViewGroupPanelTopText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组方式:  的本地化字符串。
        /// </summary>
        public static string GridViewGroupPanelTopTextGrouped {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopTextGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateAverage {
            get {
                return ResourceManager.GetString("Pivot_AggregateAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateCount {
            get {
                return ResourceManager.GetString("Pivot_AggregateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateMax {
            get {
                return ResourceManager.GetString("Pivot_AggregateMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateMin {
            get {
                return ResourceManager.GetString("Pivot_AggregateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1}: {0} 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateP0ofP1 {
            get {
                return ResourceManager.GetString("Pivot_AggregateP0ofP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateProduct {
            get {
                return ResourceManager.GetString("Pivot_AggregateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准差 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateStdDev {
            get {
                return ResourceManager.GetString("Pivot_AggregateStdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总体标准差 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateStdDevP {
            get {
                return ResourceManager.GetString("Pivot_AggregateStdDevP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 求和 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateSum {
            get {
                return ResourceManager.GetString("Pivot_AggregateSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方差 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateVar {
            get {
                return ResourceManager.GetString("Pivot_AggregateVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总体方差 的本地化字符串。
        /// </summary>
        public static string Pivot_AggregateVarP {
            get {
                return ResourceManager.GetString("Pivot_AggregateVarP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        public static string Pivot_Column {
            get {
                return ResourceManager.GetString("Pivot_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 天 的本地化字符串。
        /// </summary>
        public static string Pivot_DayGroup {
            get {
                return ResourceManager.GetString("Pivot_DayGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Pivot_Error {
            get {
                return ResourceManager.GetString("Pivot_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计 的本地化字符串。
        /// </summary>
        public static string Pivot_GrandTotal {
            get {
                return ResourceManager.GetString("Pivot_GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} 的本地化字符串。
        /// </summary>
        public static string Pivot_GroupP0AggregateP1 {
            get {
                return ResourceManager.GetString("Pivot_GroupP0AggregateP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 小时 的本地化字符串。
        /// </summary>
        public static string Pivot_HourGroup {
            get {
                return ResourceManager.GetString("Pivot_HourGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 分钟 的本地化字符串。
        /// </summary>
        public static string Pivot_MinuteGroup {
            get {
                return ResourceManager.GetString("Pivot_MinuteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 月 的本地化字符串。
        /// </summary>
        public static string Pivot_MonthGroup {
            get {
                return ResourceManager.GetString("Pivot_MonthGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 总共 的本地化字符串。
        /// </summary>
        public static string Pivot_P0Total {
            get {
                return ResourceManager.GetString("Pivot_P0Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 季 的本地化字符串。
        /// </summary>
        public static string Pivot_QuarterGroup {
            get {
                return ResourceManager.GetString("Pivot_QuarterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        public static string Pivot_Row {
            get {
                return ResourceManager.GetString("Pivot_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 秒 的本地化字符串。
        /// </summary>
        public static string Pivot_SecondGroup {
            get {
                return ResourceManager.GetString("Pivot_SecondGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小计 的本地化字符串。
        /// </summary>
        public static string Pivot_TotalP0 {
            get {
                return ResourceManager.GetString("Pivot_TotalP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值: {0} 的本地化字符串。
        /// </summary>
        public static string Pivot_Value {
            get {
                return ResourceManager.GetString("Pivot_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string Pivot_Values {
            get {
                return ResourceManager.GetString("Pivot_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 周 的本地化字符串。
        /// </summary>
        public static string Pivot_WeekGroup {
            get {
                return ResourceManager.GetString("Pivot_WeekGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - 年 的本地化字符串。
        /// </summary>
        public static string Pivot_YearGroup {
            get {
                return ResourceManager.GetString("Pivot_YearGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_And {
            get {
                return ResourceManager.GetString("PivotFieldList_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序排序 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_AscendingBy {
            get {
                return ResourceManager.GetString("PivotFieldList_AscendingBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基于字段: 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_BaseField {
            get {
                return ResourceManager.GetString("PivotFieldList_BaseField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基于项: 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_BaseItem {
            get {
                return ResourceManager.GetString("PivotFieldList_BaseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头是 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_BeginsWith {
            get {
                return ResourceManager.GetString("PivotFieldList_BeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_BottomItems {
            get {
                return ResourceManager.GetString("PivotFieldList_BottomItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  :  的本地化字符串。
        /// </summary>
        public static string PivotFieldList_By {
            get {
                return ResourceManager.GetString("PivotFieldList_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选定要汇总的字段. 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ChooseAggregateFunction {
            get {
                return ResourceManager.GetString("PivotFieldList_ChooseAggregateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择字段进行数据透视: 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ChooseFieldsToAddToReport {
            get {
                return ResourceManager.GetString("PivotFieldList_ChooseFieldsToAddToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空计算 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ClearCalculations {
            get {
                return ResourceManager.GetString("PivotFieldList_ClearCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空筛选 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ClearFilter {
            get {
                return ResourceManager.GetString("PivotFieldList_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表头 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ColumnLabels {
            get {
                return ResourceManager.GetString("PivotFieldList_ColumnLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相等 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ConditionEquals {
            get {
                return ResourceManager.GetString("PivotFieldList_ConditionEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Contains {
            get {
                return ResourceManager.GetString("PivotFieldList_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动更新 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_DeferLayoutUpdate {
            get {
                return ResourceManager.GetString("PivotFieldList_DeferLayoutUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序排序 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_DescendingBy {
            get {
                return ResourceManager.GetString("PivotFieldList_DescendingBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 差异 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_DifferenceFrom {
            get {
                return ResourceManager.GetString("PivotFieldList_DifferenceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头不是 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_DoesNotBeginWith {
            get {
                return ResourceManager.GetString("PivotFieldList_DoesNotBeginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_DoesNotContains {
            get {
                return ResourceManager.GetString("PivotFieldList_DoesNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结尾不是 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_DoesNotEndWith {
            get {
                return ResourceManager.GetString("PivotFieldList_DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_DoesNotEqual {
            get {
                return ResourceManager.GetString("PivotFieldList_DoesNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖动字段到下面的区域: 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_DragFieldsBetweenAreasBelow {
            get {
                return ResourceManager.GetString("PivotFieldList_DragFieldsBetweenAreasBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结尾是 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_EndsWith {
            get {
                return ResourceManager.GetString("PivotFieldList_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 ({0}) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_FilterItemsP0 {
            get {
                return ResourceManager.GetString("PivotFieldList_FilterItemsP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式: 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Format {
            get {
                return ResourceManager.GetString("PivotFieldList_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式化单元格 ({0}) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_FormatCellsP0 {
            get {
                return ResourceManager.GetString("PivotFieldList_FormatCellsP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格格式 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_GeneralFormat {
            get {
                return ResourceManager.GetString("PivotFieldList_GeneralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略大小写 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_IgnoreCase {
            get {
                return ResourceManager.GetString("PivotFieldList_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Index {
            get {
                return ResourceManager.GetString("PivotFieldList_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 介于 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_IsBetween {
            get {
                return ResourceManager.GetString("PivotFieldList_IsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_IsGreaterThan {
            get {
                return ResourceManager.GetString("PivotFieldList_IsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于等于 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_IsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("PivotFieldList_IsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_IsLessThan {
            get {
                return ResourceManager.GetString("PivotFieldList_IsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于等于 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_IsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("PivotFieldList_IsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不介于 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_IsNotBetween {
            get {
                return ResourceManager.GetString("PivotFieldList_IsNotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本筛选 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_LabelFilter {
            get {
                return ResourceManager.GetString("PivotFieldList_LabelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本筛选 ({0}) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_LabelFilterP0 {
            get {
                return ResourceManager.GetString("PivotFieldList_LabelFilterP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级统计... 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_MoreAggregateOptions {
            get {
                return ResourceManager.GetString("PivotFieldList_MoreAggregateOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级计算... 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_MoreCalculationOptions {
            get {
                return ResourceManager.GetString("PivotFieldList_MoreCalculationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级排序... 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_MoreSortingOptions {
            get {
                return ResourceManager.GetString("PivotFieldList_MoreSortingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无计算 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_NoCalculation {
            get {
                return ResourceManager.GetString("PivotFieldList_NoCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (null) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Null {
            get {
                return ResourceManager.GetString("PivotFieldList_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字格式化 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_NumberFormat {
            get {
                return ResourceManager.GetString("PivotFieldList_NumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 不同于 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_PercentDifferenceFrom {
            get {
                return ResourceManager.GetString("PivotFieldList_PercentDifferenceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_PercentOf {
            get {
                return ResourceManager.GetString("PivotFieldList_PercentOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的列 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_PercentOfColumnTotal {
            get {
                return ResourceManager.GetString("PivotFieldList_PercentOfColumnTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的累计 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_PercentOfGrandTotal {
            get {
                return ResourceManager.GetString("PivotFieldList_PercentOfGrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的行 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_PercentOfRowTotal {
            get {
                return ResourceManager.GetString("PivotFieldList_PercentOfRowTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % Running Total In 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_PercentRunningTotalIn {
            get {
                return ResourceManager.GetString("PivotFieldList_PercentRunningTotalIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请刷新透视图 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_PleaseRefreshThePivot {
            get {
                return ResourceManager.GetString("PivotFieldList_PleaseRefreshThePivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排名从大到小 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_RankLargestToSmallest {
            get {
                return ResourceManager.GetString("PivotFieldList_RankLargestToSmallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排名从小到大 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_RankSmallestToLargest {
            get {
                return ResourceManager.GetString("PivotFieldList_RankSmallestToLargest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Refresh {
            get {
                return ResourceManager.GetString("PivotFieldList_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (下一个) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_RelativeToNext {
            get {
                return ResourceManager.GetString("PivotFieldList_RelativeToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (上一个) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_RelativeToPrevious {
            get {
                return ResourceManager.GetString("PivotFieldList_RelativeToPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ReportFilter {
            get {
                return ResourceManager.GetString("PivotFieldList_ReportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行头 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_RowLabels {
            get {
                return ResourceManager.GetString("PivotFieldList_RowLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_RunningTotalIn {
            get {
                return ResourceManager.GetString("PivotFieldList_RunningTotalIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (全选) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SelectAll {
            get {
                return ResourceManager.GetString("PivotFieldList_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选项 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SelectItem {
            get {
                return ResourceManager.GetString("PivotFieldList_SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选项 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SelectItems {
            get {
                return ResourceManager.GetString("PivotFieldList_SelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SetAverageAggregate {
            get {
                return ResourceManager.GetString("PivotFieldList_SetAverageAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SetCountAggregate {
            get {
                return ResourceManager.GetString("PivotFieldList_SetCountAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SetIndexTotalFormat {
            get {
                return ResourceManager.GetString("PivotFieldList_SetIndexTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的累计 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SetPercentOfGrandTotalFormat {
            get {
                return ResourceManager.GetString("PivotFieldList_SetPercentOfGrandTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 求和 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SetSumAggregate {
            get {
                return ResourceManager.GetString("PivotFieldList_SetSumAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Show {
            get {
                return ResourceManager.GetString("PivotFieldList_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示空组 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ShowEmptyGroups {
            get {
                return ResourceManager.GetString("PivotFieldList_ShowEmptyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示项目 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ShowItemsForWhich {
            get {
                return ResourceManager.GetString("PivotFieldList_ShowItemsForWhich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show items for which the label 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ShowItemsForWhichTheLabel {
            get {
                return ResourceManager.GetString("PivotFieldList_ShowItemsForWhichTheLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示值为 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ShowValuesAs {
            get {
                return ResourceManager.GetString("PivotFieldList_ShowValuesAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示值为 ({0}) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ShowValuesAsP0 {
            get {
                return ResourceManager.GetString("PivotFieldList_ShowValuesAsP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SortAtoZ {
            get {
                return ResourceManager.GetString("PivotFieldList_SortAtoZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序选项 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SortOptions {
            get {
                return ResourceManager.GetString("PivotFieldList_SortOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 ({0}) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SortP0 {
            get {
                return ResourceManager.GetString("PivotFieldList_SortP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SortZtoA {
            get {
                return ResourceManager.GetString("PivotFieldList_SortZtoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式应设为可识别的格式. 格式化的结果将直接应用在求和、平均、最值等运算中. 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_StringFormatDescription {
            get {
                return ResourceManager.GetString("PivotFieldList_StringFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汇总数值 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_SummarizeValuesBy {
            get {
                return ResourceManager.GetString("PivotFieldList_SummarizeValuesBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此操作需要更多信息. 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_TheActionRequiresMoreRecentInformation {
            get {
                return ResourceManager.GetString("PivotFieldList_TheActionRequiresMoreRecentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前十个 ({0}) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Top10FilterP0 {
            get {
                return ResourceManager.GetString("PivotFieldList_Top10FilterP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Top10Items {
            get {
                return ResourceManager.GetString("PivotFieldList_Top10Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Top10Percent {
            get {
                return ResourceManager.GetString("PivotFieldList_Top10Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 求和 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Top10Sum {
            get {
                return ResourceManager.GetString("PivotFieldList_Top10Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_TopItems {
            get {
                return ResourceManager.GetString("PivotFieldList_TopItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前10个 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_TopTenFilter {
            get {
                return ResourceManager.GetString("PivotFieldList_TopTenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_Update {
            get {
                return ResourceManager.GetString("PivotFieldList_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值筛选 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ValueFilter {
            get {
                return ResourceManager.GetString("PivotFieldList_ValueFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值筛选 ({0}) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ValueFilterP0 {
            get {
                return ResourceManager.GetString("PivotFieldList_ValueFilterP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值汇总 ({0}) 的本地化字符串。
        /// </summary>
        public static string PivotFieldList_ValueSummarizationP0 {
            get {
                return ResourceManager.GetString("PivotFieldList_ValueSummarizationP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值 的本地化字符串。
        /// </summary>
        public static string PivotFiledList_Values {
            get {
                return ResourceManager.GetString("PivotFiledList_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 季度 的本地化字符串。
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Q 的本地化字符串。
        /// </summary>
        public static string QuarterShort {
            get {
                return ResourceManager.GetString("QuarterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        public static string RadDataPagerEllipsisString {
            get {
                return ResourceManager.GetString("RadDataPagerEllipsisString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 / 的本地化字符串。
        /// </summary>
        public static string RadDataPagerOf {
            get {
                return ResourceManager.GetString("RadDataPagerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        public static string RadDataPagerPage {
            get {
                return ResourceManager.GetString("RadDataPagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周 的本地化字符串。
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W 的本地化字符串。
        /// </summary>
        public static string WeekShort {
            get {
                return ResourceManager.GetString("WeekShort", resourceCulture);
            }
        }
    }
}
